### ISSUE TITLE
Easy to mix up with VCR.py

### ISSUE THREAD

**Issue by keikoro** [obspy/vcr#13]
Hi there, just wanted to leave some feedback regarding your choice of name...

I was actually looking for VCR.py on PyPI but this popped up first because I was only searching for "vcr" and this library gets listed first (mostly due to its name I'm guessing; going by GitHub stars, this repo is a lot less popular and active than the "original").

Is this intentional? I found it quite confusing / misleading.

**Comment by barsch** [comment]
> Is this intentional?

nope

>I found it quite confusing / misleading.

fixed by removing it from pypi
